name: Comment on Good First Issue

on:
  issues:
    types:
      - labeled

jobs:
  comment:
    runs-on: ubuntu-latest

    steps:
      - name: Check if labeled as "good first issue"
        id: check_label
        run: |
          echo ::set-output name=is_good_first_issue::${{ contains(github.event.issue.labels.*.name, 'good first issue') }}

      - name: Add comment
        if: steps.check_label.outputs.is_good_first_issue == 'true'
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { issue, context } = github;
            const paragraph = `
              This is a multiline comment.
              It can span multiple lines.
              Write your paragraph here.
              You can include line breaks and formatting as needed.
            `;
            const comment = issue.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: paragraph
            });
            return comment;
