name: Comment on Good First Issue

on:
  issues:
    types:
      - labeled

jobs:
  add-comment:
    if: github.event.label.name == 'Good first issue'
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Add comment
        uses: actions/github-script@v6
        with:
          issue-number: ${{ github.event.issue.number }}
          body: |
            ### Good first issue - notes for new contributors

            This issue is suited to new contributors because it does not require understanding of the.